#!/bin/bash

function print_help {
    echo "Usage:"
    echo "  $(basename $0) [-h] [-i interval] <time>"
    echo "        -h ... print this help and exit"
    echo "        -i ... polling interval in seconds (default is 1)"
    echo "        -v ... be verbose (say what you are doing)"
    echo "      time ... time in following formats:"
    echo "                 YYYY-MM-DDThh:mm"
    echo "                 hh:mm"
    echo "                 YYYY-MM-DD"
}

# Parse arguments
INTERVAL=58
VERBOSE=""
while [[ $# -ne 0 ]]; do
    case ${1} in
        -h|--help)
            print_help
            exit 0
            ;;
        -v|--verbose)
            VERBOSE=1
            ;;
        -i|--interval)
            shift
            INTERVAL="${1}"
            ;;
        [0-9][0-9]:[0-9][0-9]*)
            TIMESTAMP="$(echo $(date +%Y-%m-%d)T${1} | cut -c -16)"
            ;;
        [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9])
            TIMESTAMP="${1}T00:00"
            ;;
        [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]*)
            TIMESTAMP="$(echo ${1} | cut -c -16)"
            ;;
        *)
            echo "Invalid parameter ${1}"
            exit 1
            ;;
    esac
    shift
done
[[ -z "${TIMESTAMP}" ]] && { echo "Missing valid timestamp"; exit 1; }

function kolikje () {
    TZ='Europe/Prague' tedje=$(date -Iminutes | cut -d + -f 1)
    [[ -n "${VERBOSE}" ]] && echo -e "Ted je: ${tedje}\nCekam na: ${TIMESTAMP}\n" 1>&2
    echo "${tedje}"
    return 0
}

while [[ "$(kolikje)" < "${TIMESTAMP}" ]]; do
    sleep ${INTERVAL}
done

exit 0
