#!/bin/bash

NC="/usr/bin/netcat"
SENSOR="28-000001b4754f"
TIMEOUT="10"

[[ -n "${1}" ]] && SENSOR="${1}"

echo "${SENSOR}" | timeout ${TIMEOUT}s "${NC}" -i ${TIMEOUT} -w ${TIMEOUT} sensor 9998 || exit 1

exit 0
#EOF
