#!/bin/bash

KOTELPATH='/root/bin'

DRYRUN=''
LOW='23'
HIGH='24'
TIME="60"

function print_help {
    echo "Usage:"
    echo "  $(basename $0) [-h|-d] <low> <high>"
    echo "        -h ... print this help"
    echo "        -d ... dry run; just tell me what you wanna do"
    echo "        -t ... number of seconds between runs (default is 60)"
    echo "       low ... the low temperature limit (default is 23)"
    echo "      high ... the upper temperature limit (default is 24)"
}

# Parse arguments
L=''
while [[ $# -ne 0 ]]; do
    case ${1} in
        -h)
            print_help
            exit 0
            ;;
        -t|--time)
            shift
            TIME="${1}"
            ;;
        -d|--dry)
            DRYRUN='YES'
            ;;
        [0-9]|[0-9][0-9])
            [[ -z "${L}" ]] && \
                { LOW="${1}"; L='x'; } || \
                HIGH="${1}"
            ;;
        *)
            echo "Invalid parameter ${1}"
            exit 1
            ;;
    esac
    shift
done

while true; do
    STATUS="$( ${KOTELPATH}/kotel status)" || { echo 'Error getting the current kotel status'; exit 1; }
    CURRENT="$( ${KOTELPATH}/current)" || { echo 'Error getting the current kotel temperature'; exit 1; }
    T=$(( ${CURRENT} / 1000 )) || { echo "Error converting temperature"; exit 1; }

    NEWSTATUS=''
    [[ ${T} -gt ${HIGH} ]] && NEWSTATUS='stopped'
    [[ ${T} -lt ${LOW} ]] && NEWSTATUS='started'
    [[ -z "${NEWSTATUS}" ]] && NEWSTATUS="${STATUS}"

    date "+%Y-%m-%d %H:%M:%S"
    echo Temp: $T
    echo Newstatus: $NEWSTATUS
    echo Status: $STATUS
    echo Low: $LOW
    echo High: $HIGH

    if [[ "${NEWSTATUS}" = "${STATUS}" ]]; then
        echo "Kotel already in required state"
    else
        echo "Switching kotel to status ${NEWSTATUS}"
        [[ -z "${DRYRUN}" ]] && \
            ${KOTELPATH}/kotel ${NEWSTATUS} || \
            echo "Dry run: ${KOTELPATH}/kotel ${NEWSTATUS}"
    fi
    sleep ${TIME}
    echo
done

exit 0
#EOF
